<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Storage;
use App\Models\ProductImage;
use App\Models\Product;
use Illuminate\Support\Facades\File;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            [
                'name' => 'Vi Criança',
                'origin' => 'Catalunya',
                'year' => 2020,
                'wine_type_id' => 1,
                'description' => 'Vi de prova per a la prova',
                'price_demanded' => 45,
                'quantity' => 1,
                'image' => 'https://images.unsplash.com/photo-1584916201218-f4242ceb4809?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
            ],
            [
                'name' => 'Vi i sen va',
                'origin' => 'Madrid',
                'year' => 2018,
                'wine_type_id' => 2,
                'description' => 'Vi de prova per a la prova',
                'price_demanded' => 100,
                'quantity' => 1,
                'image' => 'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
            ],
            [
                'name' => 'Vi no vi',
                'origin' => 'França',
                'year' => 2017,
                'wine_type_id' => 3,
                'description' => 'Vi de prova per a la prova',
                'price_demanded' => 25,
                'quantity' => 1,
                'image' => 'https://images.unsplash.com/photo-1559564114-569052b65578?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
            ],
            [
                'name' => 'Louis Latour ',
                'origin' => 'França',
                'year' => 2023,
                'wine_type_id' => 2,
                'description' => 'Vi de prova per a la prova',
                'price_demanded' => 100,
                'quantity' => 1,
                'image' => 'https://images.unsplash.com/photo-1504502350688-00f5fcbd7f52?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
            ],
            [
                'name' => 'Palacio de Bornos',
                'origin' => 'Rueda',
                'year' => 2023,
                'wine_type_id' => 1,
                'description' => 'Vi de prova per a la prova',
                'price_demanded' => 100,
                'quantity' => 1,
                'image' => 'https://images.unsplash.com/photo-1585553616435-2dc0a54e271d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
            ],
            [
                'name' => 'Vega Sicilia Único',
                'origin' => 'Ribera del Duero',
                'year' => 2012,
                'wine_type_id' => 1,
                'description' => 'Vino tinto legendario con gran capacidad de guarda.',
                'price_demanded' => 350,
                'quantity' => 2,
                'image' => 'https://images.unsplash.com/photo-1559564114-569052b65578?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
            ],
            [
                'name' => 'Dominio de Pingus',
                'origin' => 'Ribera del Duero',
                'year' => 2018,
                'wine_type_id' => 1,
                'description' => 'Vino exclusivo, potente y muy elegante.',
                'price_demanded' => 890,
                'quantity' => 1,
                'image' => 'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
            ],
            [
                'name' => 'L\'Ermita',
                'origin' => 'Priorat',
                'year' => 2017,
                'wine_type_id' => 1,
                'description' => 'La joya del Priorat, pura expresión del terroir.',
                'price_demanded' => 950,
                'quantity' => 1,
                'image' => 'https://images.unsplash.com/photo-1559564114-569052b65578?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
            ],
            [
                'name' => 'Château Lafite Rothschild',
                'origin' => 'Burdeos',
                'year' => 2015,
                'wine_type_id' => 1,
                'description' => 'Primer cru bordelés, finura inigualable.',
                'price_demanded' => 800,
                'quantity' => 3,
                'image' => 'https://images.unsplash.com/photo-1504502350688-00f5fcbd7f52?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
            ],
            [
                'name' => 'Château Margaux',
                'origin' => 'Burdeos',
                'year' => 2010,
                'wine_type_id' => 1,
                'description' => 'Elegancia clásica y aromas florales.',
                'price_demanded' => 750,
                'quantity' => 2,
                'image' => 'https://images.unsplash.com/photo-1559564114-569052b65578?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
            ],
            [
                'name' => 'Domaine de la Romanée-Conti',
                'origin' => 'Borgoña',
                'year' => 2014,
                'wine_type_id' => 1,
                'description' => 'El Pinot Noir más buscado del mundo.',
                'price_demanded' => 4500,
                'quantity' => 1,
                'image' => 'https://images.unsplash.com/photo-1559564114-569052b65578?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
            ],
            [
                'name' => 'Sassicaia',
                'origin' => 'Toscana',
                'year' => 2016,
                'wine_type_id' => 1,
                'description' => 'El pionero de los Súper Toscanos.',
                'price_demanded' => 250,
                'quantity' => 4,
                'image' => 'https://images.unsplash.com/photo-1559564114-569052b65578?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
            ],
            [
                'name' => 'Tignanello',
                'origin' => 'Toscana',
                'year' => 2018,
                'wine_type_id' => 1,
                'description' => 'Moderno, seductor y complejo.',
                'price_demanded' => 120,
                'quantity' => 6,
                'image' => 'https://images.unsplash.com/photo-1559564114-569052b65578?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
            ],
            [
                'name' => 'Opus One',
                'origin' => 'Napa Valley',
                'year' => 2017,
                'wine_type_id' => 1,
                'description' => 'El icónico ensamblaje californiano.',
                'price_demanded' => 380,
                'quantity' => 2,
                'image' => 'https://images.unsplash.com/photo-1559564114-569052b65578?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
            ],
            [
                'name' => 'Castillo Ygay Gran Reserva Especial',
                'origin' => 'Rioja',
                'year' => 2010,
                'wine_type_id' => 1,
                'description' => 'Clásico riojano con evolución perfecta.',
                'price_demanded' => 150,
                'quantity' => 3,
                'image' => 'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
            ],
            [
                'name' => 'La Rioja Alta Gran Reserva 890',
                'origin' => 'Rioja',
                'year' => 2005,
                'wine_type_id' => 1,
                'description' => 'Tradición y nobleza en cada copa.',
                'price_demanded' => 130,
                'quantity' => 2,
                'image' => 'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
            ],
            [
                'name' => 'Viña Ardanza Reserva',
                'origin' => 'Rioja',
                'year' => 2015,
                'wine_type_id' => 1,
                'description' => 'El reserva por excelencia de España.',
                'price_demanded' => 35,
                'quantity' => 10,
                'image' => 'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
            ],
            [
                'name' => 'Prado Enea Gran Reserva',
                'origin' => 'Rioja',
                'year' => 2014,
                'wine_type_id' => 1,
                'description' => 'Equilibrio y finura excepcionales.',
                'price_demanded' => 60,
                'quantity' => 5,
                'image' => 'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
            ],
            [
                'name' => 'Macán',
                'origin' => 'Rioja',
                'year' => 2016,
                'wine_type_id' => 1,
                'description' => 'Alianza entre Rothschild y Vega Sicilia.',
                'price_demanded' => 75,
                'quantity' => 4,
                'image' => 'https://images.unsplash.com/photo-1559564114-569052b65578?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
            ],
            [
                'name' => 'Contino Reserva',
                'origin' => 'Rioja',
                'year' => 2017,
                'wine_type_id' => 1,
                'description' => 'El concepto de château en Rioja.',
                'price_demanded' => 30,
                'quantity' => 6,
                'image' => 'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
            ],
            [
                'name' => 'Cirsion',
                'origin' => 'Rioja',
                'year' => 2018,
                'wine_type_id' => 1,
                'description' => 'Innovación y sedosidad extrema.',
                'price_demanded' => 180,
                'quantity' => 2,
                'image' => 'https://images.unsplash.com/photo-1559564114-569052b65578?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
            ],
            [
                'name' => 'Torre Muga',
                'origin' => 'Rioja',
                'year' => 2019,
                'wine_type_id' => 1,
                'description' => 'Tinto moderno y corpulento.',
                'price_demanded' => 70,
                'quantity' => 4,
                'image' => 'https://images.unsplash.com/photo-1559564114-569052b65578?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
            ],
            [
                'name' => 'Valbuena 5º',
                'origin' => 'Ribera del Duero',
                'year' => 2017,
                'wine_type_id' => 1,
                'description' => 'El hermano pequeño de Único, excepcional.',
                'price_demanded' => 140,
                'quantity' => 4,
                'image' => 'https://images.unsplash.com/photo-1559564114-569052b65578?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
            ],
            [
                'name' => 'Alión',
                'origin' => 'Ribera del Duero',
                'year' => 2018,
                'wine_type_id' => 1,
                'description' => 'Potencia y elegancia modernas.',
                'price_demanded' => 80,
                'quantity' => 6,
                'image' => 'https://images.unsplash.com/photo-1559564114-569052b65578?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
            ],
            [
                'name' => 'Aalto PS',
                'origin' => 'Ribera del Duero',
                'year' => 2019,
                'wine_type_id' => 1,
                'description' => 'Selección de pagos extraordinarios.',
                'price_demanded' => 95,
                'quantity' => 3,
                'image' => 'https://images.unsplash.com/photo-1559564114-569052b65578?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
            ],
            [
                'name' => 'Malleolus de Sanchomartín',
                'origin' => 'Ribera del Duero',
                'year' => 2018,
                'wine_type_id' => 1,
                'description' => 'Tinto de pago, intenso y mineral.',
                'price_demanded' => 120,
                'quantity' => 2,
                'image' => 'https://images.unsplash.com/photo-1559564114-569052b65578?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
            ],
            [
                'name' => 'Flor de Pingus',
                'origin' => 'Ribera del Duero',
                'year' => 2019,
                'wine_type_id' => 1,
                'description' => 'Mucha fruta y madera sublime.',
                'price_demanded' => 150,
                'quantity' => 3,
                'image' => 'https://images.unsplash.com/photo-1559564114-569052b65578?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
            ],
            [
                'name' => 'Hacienda Monasterio Reserva',
                'origin' => 'Ribera del Duero',
                'year' => 2016,
                'wine_type_id' => 1,
                'description' => 'Equilibrio perfecto, gran textura.',
                'price_demanded' => 50,
                'quantity' => 6,
                'image' => 'https://images.unsplash.com/photo-1559564114-569052b65578?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
            ],
            [
                'name' => 'Teso La Monja',
                'origin' => 'Toro',
                'year' => 2015,
                'wine_type_id' => 1,
                'description' => 'La máxima expresión de la Tinta de Toro.',
                'price_demanded' => 1000,
                'quantity' => 1,
                'image' => 'https://images.unsplash.com/photo-1584916201218-f4242ceb4809?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
            ],
            [
                'name' => 'Numanthia',
                'origin' => 'Toro',
                'year' => 2016,
                'wine_type_id' => 1,
                'description' => 'Estructura monumental y fruta negra.',
                'price_demanded' => 45,
                'quantity' => 8,
                'image' => 'https://images.unsplash.com/photo-1584916201218-f4242ceb4809?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
            ],
            [
                'name' => 'San Román',
                'origin' => 'Toro',
                'year' => 2018,
                'wine_type_id' => 1,
                'description' => 'Vigoroso, terroso y profundo.',
                'price_demanded' => 35,
                'quantity' => 10,
                'image' => 'https://images.unsplash.com/photo-1584916201218-f4242ceb4809?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
            ],
            [
                'name' => 'Pintia',
                'origin' => 'Toro',
                'year' => 2017,
                'wine_type_id' => 1,
                'description' => 'El Toro de la galaxia Vega Sicilia.',
                'price_demanded' => 50,
                'quantity' => 6,
                'image' => 'https://images.unsplash.com/photo-1584916201218-f4242ceb4809?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
            ],
            [
                'name' => 'Victorino',
                'origin' => 'Toro',
                'year' => 2019,
                'wine_type_id' => 1,
                'description' => 'Energía y raza de Toro.',
                'price_demanded' => 40,
                'quantity' => 6,
                'image' => 'https://images.unsplash.com/photo-1584916201218-f4242ceb4809?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
            ],
            [
                'name' => 'Clos Erasmus',
                'origin' => 'Priorat',
                'year' => 2019,
                'wine_type_id' => 1,
                'description' => 'Garnacha de pureza celestial.',
                'price_demanded' => 200,
                'quantity' => 2,
                'image' => 'https://images.unsplash.com/photo-1559564114-569052b65578?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
            ],
            [
                'name' => 'Finca Dofí',
                'origin' => 'Priorat',
                'year' => 2018,
                'wine_type_id' => 1,
                'description' => 'Mineralidad, frescura y fruta roja.',
                'price_demanded' => 70,
                'quantity' => 4,
                'image' => 'https://images.unsplash.com/photo-1559564114-569052b65578?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
            ],
            [
                'name' => 'Les Terrasses',
                'origin' => 'Priorat',
                'year' => 2019,
                'wine_type_id' => 1,
                'description' => 'Un viaje a la historia del Priorat.',
                'price_demanded' => 35,
                'quantity' => 6,
                'image' => 'https://images.unsplash.com/photo-1559564114-569052b65578?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
            ],
            [
                'name' => 'Martinet Bru',
                'origin' => 'Priorat',
                'year' => 2020,
                'wine_type_id' => 1,
                'description' => 'Entrada perfecta al universo Mas Martinet.',
                'price_demanded' => 25,
                'quantity' => 12,
                'image' => 'https://images.unsplash.com/photo-1559564114-569052b65578?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
            ],
            [
                'name' => 'Vall Llach',
                'origin' => 'Priorat',
                'year' => 2017,
                'wine_type_id' => 1,
                'description' => 'Cariñenas viejas e impresionantes.',
                'price_demanded' => 65,
                'quantity' => 3,
                'image' => 'https://images.unsplash.com/photo-1559564114-569052b65578?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
            ],
            [
                'name' => 'La Faraona',
                'origin' => 'Bierzo',
                'year' => 2018,
                'wine_type_id' => 1,
                'description' => 'Magia en Corullón, etéreo y sutil.',
                'price_demanded' => 700,
                'quantity' => 1,
                'image' => 'https://images.unsplash.com/photo-1559564114-569052b65578?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
            ],
            [
                'name' => 'Corullón',
                'origin' => 'Bierzo',
                'year' => 2019,
                'wine_type_id' => 1,
                'description' => 'Mencía vibrante y expresiva.',
                'price_demanded' => 40,
                'quantity' => 6,
                'image' => 'https://images.unsplash.com/photo-1559564114-569052b65578?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
            ],
            [
                'name' => 'Pétalos del Bierzo',
                'origin' => 'Bierzo',
                'year' => 2020,
                'wine_type_id' => 1,
                'description' => 'Vino floral, jugoso y muy bebible.',
                'price_demanded' => 18,
                'quantity' => 15,
                'image' => 'https://images.unsplash.com/photo-1559564114-569052b65578?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
            ],
            [
                'name' => 'Quincha Corral',
                'origin' => 'Alicante',
                'year' => 2015,
                'wine_type_id' => 1,
                'description' => 'Monastrell goloso de cepas viejas.',
                'price_demanded' => 55,
                'quantity' => 4,
                'image' => 'https://images.unsplash.com/photo-1559564114-569052b65578?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
            ],
            [
                'name' => 'Blecua',
                'origin' => 'Somontano',
                'year' => 2014,
                'wine_type_id' => 1,
                'description' => 'Siete mejores barricas del Somontano.',
                'price_demanded' => 90,
                'quantity' => 2,
                'image' => 'https://images.unsplash.com/photo-1559564114-569052b65578?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
            ],
            [
                'name' => 'Château Mouton Rothschild',
                'origin' => 'Burdeos',
                'year' => 2010,
                'wine_type_id' => 1,
                'description' => 'Opulencia, fruta negra y especias.',
                'price_demanded' => 700,
                'quantity' => 2,
                'image' => 'https://images.unsplash.com/photo-1504502350688-00f5fcbd7f52?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
            ],
            [
                'name' => 'Pétrus',
                'origin' => 'Pomerol',
                'year' => 2015,
                'wine_type_id' => 1,
                'description' => 'El Merlot más legendario y caro.',
                'price_demanded' => 3500,
                'quantity' => 1,
                'image' => 'https://images.unsplash.com/photo-1504502350688-00f5fcbd7f52?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
            ],
            [
                'name' => 'Cheval Blanc',
                'origin' => 'Saint-Émilion',
                'year' => 2016,
                'wine_type_id' => 1,
                'description' => 'Cabernet Franc celestial.',
                'price_demanded' => 850,
                'quantity' => 2,
                'image' => 'https://images.unsplash.com/photo-1504502350688-00f5fcbd7f52?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
            ],
            [
                'name' => 'Haut-Brion',
                'origin' => 'Pessac-Léognan',
                'year' => 2018,
                'wine_type_id' => 1,
                'description' => 'Notas ahumadas e intensidad incomparable.',
                'price_demanded' => 600,
                'quantity' => 2,
                'image' => 'https://images.unsplash.com/photo-1504502350688-00f5fcbd7f52?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
            ],
            [
                'name' => 'Grange',
                'origin' => 'Australia',
                'year' => 2015,
                'wine_type_id' => 1,
                'description' => 'El referente máximo del Shiraz australiano.',
                'price_demanded' => 650,
                'quantity' => 2,
                'image' => 'https://images.unsplash.com/photo-1559564114-569052b65578?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
            ],
            [
                'name' => 'Screaming Eagle',
                'origin' => 'Napa Valley',
                'year' => 2018,
                'wine_type_id' => 1,
                'description' => 'Vino de culto californiano inalcanzable.',
                'price_demanded' => 4500,
                'quantity' => 1,
                'image' => 'https://images.unsplash.com/photo-1559564114-569052b65578?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
            ],
            [
                'name' => 'Blanco Nieva Pie Franco',
                'origin' => 'Rueda',
                'year' => 2021,
                'wine_type_id' => 2,
                'description' => 'Verdejo vibrante de viñas prefiloxéricas.',
                'price_demanded' => 16,
                'quantity' => 10,
                'image' => 'https://images.unsplash.com/photo-1585553616435-2dc0a54e271d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
            ],
            [
                'name' => 'Pazo Señorans Selección de Añada',
                'origin' => 'Rías Baixas',
                'year' => 2013,
                'wine_type_id' => 2,
                'description' => 'Albariño de guarda, sublime.',
                'price_demanded' => 45,
                'quantity' => 4,
                'image' => 'https://images.unsplash.com/photo-1585553616435-2dc0a54e271d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
            ],
            [
                'name' => 'Ossian',
                'origin' => 'Rueda',
                'year' => 2019,
                'wine_type_id' => 2,
                'description' => 'Verdejo con crianza en barrica.',
                'price_demanded' => 30,
                'quantity' => 6,
                'image' => 'https://images.unsplash.com/photo-1585553616435-2dc0a54e271d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
            ],
            [
                'name' => 'Belondrade y Lurton',
                'origin' => 'Rueda',
                'year' => 2020,
                'wine_type_id' => 2,
                'description' => 'El Verdejo que cambió las reglas.',
                'price_demanded' => 35,
                'quantity' => 4,
                'image' => 'https://images.unsplash.com/photo-1585553616435-2dc0a54e271d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
            ],
            [
                'name' => 'Marqués de Murrieta Capellanía',
                'origin' => 'Rioja',
                'year' => 2016,
                'wine_type_id' => 2,
                'description' => 'Blanco de viura complejo y longevo.',
                'price_demanded' => 50,
                'quantity' => 5,
                'image' => 'https://images.unsplash.com/photo-1585553616435-2dc0a54e271d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
            ],
            [
                'name' => 'Recaredo Turó d\'en Mota',
                'origin' => 'Penedès',
                'year' => 2008,
                'wine_type_id' => 3,
                'description' => 'Espumoso de larga crianza, mítico.',
                'price_demanded' => 120,
                'quantity' => 2,
                'image' => 'https://images.unsplash.com/photo-1559564114-569052b65578?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
            ],
        ];

        foreach ($products as $index => $product) {
            $createdProduct = Product::factory()->create(array_merge($product, [
                'user_id' => 1,
            ]));

            ProductImage::create([
                'product_id' => $createdProduct->id,
                'image_path' => $product['image'],
                'is_primary' => true,
                'order' => 0
            ]);
        }
    }
}
